import "../../app/globals.css";
import "../globals.css";

import Image from "next/image";

export const metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className="flex flex-col-reverse lg:flex-row">
        <div className="min-h-screen bg-auth-bg bg-cover flex justify-center items-center lg:w-1/2 ">
          <div className="lg:w-8/12 h-3/4">
            <div className="h-2/6 flex justify-center rounded-t-3xl  bg-primary bg-opacity-40">
              <Image
                src="/img/urban_logo.svg"
                alt="urban logo"
                width={190}
                height={89}
                priority
              />
            </div>
            <div className="pl-[50px] pt-[42px] h-4/6 bg-primary rounded-b-3xl">
              <h1 className="text-white font-bold text-2xl md:text-3xl lg:text-4xl">
                Manage your park <br /> at one glance!
              </h1>
              <ul className="text-white mt-5 md:mt-10 lg:mt8 text-base md:text-lg list-none list-inside">
                <li className="mb-2">
                  <span>-</span> Bookings & Records
                </li>
                <li className="mb-2">
                  <span>-</span> Add Park Managers
                </li>
                <li className="mb-2">
                  <span>-</span> Add Dispatch Officers
                </li>
                <li className="mb-2">
                  <span>-</span> Assign Trips & Drivers
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div className="min-h-screen flex justify-center items-center  lg:w-1/2 ">
          <div className="lg:w-9/12 p-10 ">
            {children}
            {/* </div> */}
          </div>
        </div>
      </body>
    </html>
  );
}
