import "../globals.css";
import Sidebar from "@/app/components/sidebar";
import Header from "@/app/components/headers/header";
import authOBJ from "@/common/classes/auth.class";

export const metadata = {
  title: "Urban",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  authOBJ.currentUser()
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen bg-gray-100 overflow-hidden">
          <Sidebar />
          <div className=" px-7 relative flex flex-col flex-1 overflow-y-auto overflow-x-hidden ">
            <Header />
            <div className=" p-14  my-10 rounded-xl bg-white">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
