import "./globals.css";
import Layout from "@/app/layouts";

export const metadata = {
  title: "Urban",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <Layout>{children}</Layout>;
}
