import {
  ParkUserData,
  AccountCategory,
  AccountType,
  ParkManagerData,
  addParkData,
  TripData,
} from "@/common/types";
import { GenerateID } from "@/common/utils";

export const parkOwnerData: ParkUserData = {
  accountCategory: AccountCategory.PARK,
  accountStats: "Good",
  accountType: AccountType.INDIVIDUAL,
  companyAddress: "",
  companyName: "",
  companyRc: "",
  country_: "NG",
  deviceInfo_: null,
  earnings: 0,
  email_: "",
  firstName: "",
  isAccountVerified: false,
  isEmailVerified_: false,
  lastName: "",
  lastSeen_: new Date(),
  online_: false,
  phone_: "",
  regDate_: new Date(),
  totalTrip: 0,
};
export const parkManagerDefaultData: ParkManagerData = {
  accountCategory: AccountCategory.PARK,
  accountStats: "Good",
  accountType: AccountType.PARKMANAGER,
  country_: "NG",
  deviceInfo_: null,
  earnings: 0,
  email_: "",
  firstName: "",
  isAccountVerified: false,
  isEmailVerified_: false,
  lastName: "",
  lastSeen_: new Date(),
  online_: false,
  parkToManage: "",
  parkManagerIdentity: GenerateID("UB"),
  phone_: "",
  regDate_: new Date(),
  totalTrip: 0,
};
export const addParkDefaultData: addParkData = {
  address: "",
  createdAt: "",
  dispatchOfficers: null, // Assuming the value is not provided in the input
  earnings: 0,
  isDeleted: false,
  managerId: "",
  manager_id: "",
  ownerEmail: "",
  ownerId: "",
  parkApproval: true,
  parkCity: "",
  parkNameSearch: "",
  parkRegion: "",
  parkState: "",
  phone: "",
  searchParamByID: [],
  searchParamByName: [],
  parkName: "",
  parkId: GenerateID("UB"),
  totalTrip: 0,
  successfulTrip: 0,
  scheduledTrip: 0,
  cancelledTrip: 0,
  regDate_: new Date(),
};

export const tripObject: TripData = {
  assignToDriverId: "",
  assignToProviderAgencyID: "",
  assignToProviderAgencyName: "",
  bookedSeats: 0,
  coupon: "",
  createdBy: "",
  dateCreated: new Date(),
  departureCity: "",
  departureDayInt: 0,
  departureFullDate: "",
  departureHour: "",
  departureMin: "",
  departureMonth: "",
  departurePark: "",
  departureParkId: "",
  departureTimePeriod: "",
  departureYear: 2023,
  destinationCity: "",
  fare: 0,
  isAssign: false,
  isAssignTo: "",
  isPublic: true,
  luggageType: "",
  numberOfSeats: 0,
  parkOwnerId: "",
  status: "",
  time: new Date(),
  tripCode: "",
  tripStatus: "",
  vehicleType: "",
};

export const cityLagos = [
  { value: "Ajeromi-Ifelodun", label: "Ajeromi-Ifelodun" },
  { value: "Alimosho", label: "Alimosho" },
  { value: "Amuwo-Odofin", label: "Amuwo-Odofin" },
  { value: "Apapa", label: "Apapa" },
  { value: "Badagry", label: "Badagry" },
  { value: "Epe", label: "Epe" },
  { value: "Eti Osa", label: "Eti Osa" },
  { value: "Ibeju-Lekki", label: "Ibeju-Lekki" },
  { value: "Ifako-Ijaiye", label: "Ifako-Ijaiye" },
  { value: "Ikeja", label: "Ikeja" },
  { value: "Ikorodu", label: "Ikorodu" },
  { value: "Kosofe", label: "Kosofe" },
  { value: "Lagos Island", label: "Lagos Island" },
  { value: "Lagos Mainland", label: "Lagos Mainland" },
  { value: "Mushin", label: "Mushin" },
  { value: "Ojo", label: "Ojo" },
  { value: "Oshodi-Isolo", label: "Oshodi-Isolo" },
  { value: "Shomolu", label: "Shomolu" },
  { value: "Surulere", label: "Surulere" }
];

export const cityFCT = [
  { value: "Bwari", label: "Bwari" },
  { value: "Gwagwalada", label: "Gwagwalada" },
  { value: "Kuje", label: "Kuje" },
  { value: "Kwali", label: "Kwali" },
  { value: "Municipal Area Council", label: "Municipal Area Council" }
];
